package com.andy.dolphin.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.andy.dolphin.task.Task;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "task_list".
 */
public class TaskDao extends AbstractDao<Task, String> {

    public static final String TABLENAME = "task_list";

    /**
     * Properties of entity Task.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Key = new Property(0, String.class, "key", true, "KEY");
        public final static Property Status = new Property(1, int.class, "status", false, "STATUS");
        public final static Property Url = new Property(2, String.class, "url", false, "URL");
        public final static Property FileName = new Property(3, String.class, "fileName", false, "FILE_NAME");
        public final static Property FileLength = new Property(4, int.class, "fileLength", false, "FILE_LENGTH");
        public final static Property Percent = new Property(5, float.class, "percent", false, "PERCENT");
    }

    private DaoSession daoSession;


    public TaskDao(DaoConfig config) {
        super(config);
    }

    public TaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"task_list\" (" + //
                "\"KEY\" TEXT PRIMARY KEY NOT NULL ," + // 0: key
                "\"STATUS\" INTEGER NOT NULL ," + // 1: status
                "\"URL\" TEXT NOT NULL ," + // 2: url
                "\"FILE_NAME\" TEXT," + // 3: fileName
                "\"FILE_LENGTH\" INTEGER NOT NULL ," + // 4: fileLength
                "\"PERCENT\" REAL NOT NULL );"); // 5: percent
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_task_list_KEY ON \"task_list\"" +
                " (\"KEY\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"task_list\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Task entity) {
        stmt.clearBindings();

        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(1, key);
        }
        stmt.bindLong(2, entity.getStatus());
        stmt.bindString(3, entity.getUrl());
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(4, fileName);
        }
        stmt.bindLong(5, entity.getFileLength());
        stmt.bindDouble(6, entity.getPercent());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Task entity) {
        stmt.clearBindings();

        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(1, key);
        }
        stmt.bindLong(2, entity.getStatus());
        stmt.bindString(3, entity.getUrl());
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(4, fileName);
        }
        stmt.bindLong(5, entity.getFileLength());
        stmt.bindDouble(6, entity.getPercent());
    }

    @Override
    protected final void attachEntity(Task entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }

    @Override
    public Task readEntity(Cursor cursor, int offset) {
        Task entity = new Task( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // key
                cursor.getInt(offset + 1), // status
                cursor.getString(offset + 2), // url
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fileName
                cursor.getInt(offset + 4), // fileLength
                cursor.getFloat(offset + 5) // percent
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Task entity, int offset) {
        entity.setKey(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStatus(cursor.getInt(offset + 1));
        entity.setUrl(cursor.getString(offset + 2));
        entity.setFileName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFileLength(cursor.getInt(offset + 4));
        entity.setPercent(cursor.getFloat(offset + 5));
     }

    @Override
    protected final String updateKeyAfterInsert(Task entity, long rowId) {
        return entity.getKey();
    }

    @Override
    public String getKey(Task entity) {
        if (entity != null) {
            return entity.getKey();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Task entity) {
        return entity.getKey() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
